### ISSUE TITLE
Error when run test_train.sh

### ISSUE THREAD

**Issue by wudapeng268** [rsennrich/nematus#12]
There are error message in console:
Loading data
Building model
Traceback (most recent call last):
  File "../nematus/nmt.py", line 1208, in <module>
    train(**vars(args))
  File "../nematus/nmt.py", line 795, in train
    build_model(tparams, model_options)
  File "../nematus/nmt.py", line 237, in build_model
    x, ctx = build_encoder(tparams, options, trng, use_noise, x_mask, sampling=False)
  File "../nematus/nmt.py", line 194, in build_encoder
    profile=profile)
  File "/Users/Mr.Wu/wup/nematus/nematus/layers.py", line 171, in gru_layer
    strict=True)
  File "/Users/Mr.Wu/anaconda/lib/python2.7/site-packages/theano/scan_module/scan.py", line 1041, in scan
    scan_outs = local_op(*scan_inputs)
  File "/Users/Mr.Wu/anaconda/lib/python2.7/site-packages/theano/gof/op.py", line 611, in __call__
    node = self.make_node(*inputs, **kwargs)
  File "/Users/Mr.Wu/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 538, in make_node
    inner_sitsot_out.type.dtype))
ValueError: When compiling the inner function of scan the following error has been encountered: The initial state (`outputs_info` in scan nomenclature) of variable IncSubtensor{Set;:int64:}.0 (argument number 3) has dtype float32, while the result of the inner function (`fn`) has dtype float64. This can happen if the inner function of scan results in an upcast or downcast.

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

My environment are：
Python 2.7.3
numpy 1.11.3
theano 0.8.2
Could you help me solve it ?thanks

**Comment by rsennrich** [comment]
Hello,

make sure your theano variables are set correctly (as described in the 
README file). Try setting floatX to float32:

THEANO_FLAGS=floatX=float32

best wishes,
Rico
