### ISSUE TITLE
Better message for encoder_truncate_gradient

### ISSUE THREAD

**Issue by kpu** [rsennrich/nematus#24]
Ran this (which I assume is a slightly out of date model):
```
THEANO_FLAGS=mode=FAST_RUN,floatX=float32,device=gpu,on_unused_input=warn python /fs/magni0/heafield/ro-en/nematus/nematus/translate.py -m /mnt/baldur0/rsennrich/wmt16_neural/ro-en/exp6/model.npz -k 12 -n -p 1 --suppress-unk
```

Get an error message:
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/fs/magni0/heafield/ro-en/nematus/nematus/translate.py", line 42, in translate_model
    f_init, f_next = build_sampler(tparams, option, use_noise, trng, return_alignment=return_alignment)
  File "/mnt/magni0/heafield/ro-en/nematus/nematus/nmt.py", line 393, in build_sampler
    x, ctx = build_encoder(tparams, options, trng, use_noise, x_mask=None, sampling=True)
  File "/mnt/magni0/heafield/ro-en/nematus/nematus/nmt.py", line 229, in build_encoder
    truncate_gradient=options['encoder_truncate_gradient'],
KeyError: 'encoder_truncate_gradient'
```
Note that this config does not mention `encoder_truncate_gradient` at all.

**Comment by rsennrich** [comment]
fixed. There's a separate place (compat.py) which we use to set default options for backward-compatibility. 

Default options for old models may be different from the default options in the training script (for instance, the handling of dropout is different in newly trained models, but we keep support for old models in decoding).
