### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by Avmb** [rsennrich/nematus#8]
Hi,
I'm getting some strange IOError exceptions while running Nematus training (both on baldur and meili).

Traceback (most recent call last):
  File "train.py", line 60, in <module>
    main()
  File "train.py", line 56, in main
    external_validation_script=WDIR + '/scripts/validate.sh')
  File "/fs/meili0/amiceli/nematus-dev/nematus/nmt.py", line 964, in train
    numpy.savez(saveto, history_errs=history_errs, uidx=uidx, **params)
  File "/mnt/meili0/rsennrich/tools/virtual_environment/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 574, in savez
    _savez(file, args, kwds, False)
  File "/mnt/meili0/rsennrich/tools/virtual_environment/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 642, in _savez
    zipf.write(tmpfile, arcname=fname)
  File "/usr/lib/python2.7/zipfile.py", line 1184, in write
    self.fp.write(buf)
IOError: [Errno 5] Input/output error

Python documentation says that Errno 5 is a generic I/O error.

I've also got some IOErrors of the same kind while reading the corpus in data_iterator.py but I kinda fixed them just by catching the exception and reshuffling and reopening the files.

Any ideas on what is going on?

**Comment by Avmb** [comment]
Actually, not even fixed during reads, it just appears in another place:

Traceback (most recent call last):
  File "train.py", line 66, in <module>
    main()
  File "train.py", line 62, in main
    decoder_plus_diagonal=True)
  File "/fs/meili0/amiceli/nematus-dev/nematus/nmt.py", line 917, in train
    for x, y in train:
  File "/fs/meili0/amiceli/nematus-dev/nematus/data_iterator.py", line 98, in next
    self.reset()
  File "/fs/meili0/amiceli/nematus-dev/nematus/data_iterator.py", line 69, in reset
    shuffle.main([self.source.name.replace('.shuf',''), self.target.name.replace('.shuf','')])
  File "/fs/meili0/amiceli/nematus-dev/nematus/shuffle.py", line 15, in main
    fds = [open(ff) for ff in files]
IOError: [Errno 5] Input/output error: '/mnt/baldur0/amiceli/nmt-experiments/en-ro/lrd_encdec_bpe-char/corpus.bpe.en'

**Comment by rsennrich** [comment]
Hi Antonio,

this is probably not a problem with Nematus, but with our NFS/disks, so 
let's continue this discussion offline.

best wishes,
Rico
